# Generated by Django 4.2.11 on 2024-10-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
