# Generated by Django 4.2 on 2025-02-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('lecturer', 'Lecturer')], max_length=10),
        ),
    ]
