# Generated by Django 4.2.11 on 2025-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pc_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
