# Generated by Django 4.2 on 2024-10-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing_system", "0003_customuser_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("tutor", "Tutor")],
                default="student",
                max_length=10,
            ),
        ),
    ]
