# Generated by Django 4.2.11 on 2025-03-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0004_alter_customuser_pc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pc_number',
            field=models.IntegerField(default=''),
        ),
    ]
