# Generated by Django 4.2 on 2024-10-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("queueing_system", "0004_alter_customuser_user_type"),
    ]

    operations = [
        migrations.RenameModel(old_name="CustomUser", new_name="User",),
    ]
