# Generated by Django 4.2.16 on 2024-10-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queueing_system", "0006_helprequest"),
    ]

    operations = [
        migrations.DeleteModel(name="HelpRequest",),
    ]
