# Generated by Django 4.2.11 on 2025-03-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0007_alter_helprequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
