# Generated by Django 4.2.11 on 2025-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0008_alter_helprequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pc_number',
            field=models.IntegerField(),
        ),
    ]
