# Generated by Django 4.2.11 on 2025-04-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0010_alter_customuser_pc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lab_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
