# Generated by Django 4.2.11 on 2025-04-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0011_customuser_lab_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvaslayout',
            name='name',
            field=models.CharField(default='Unnamed Lab', max_length=10),
        ),
    ]
