# Generated by Django 4.2.11 on 2025-04-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0013_alter_customuser_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queueing_system.canvaslayout'),
        ),
    ]
