# Generated by Django 4.2.11 on 2025-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0014_alter_customuser_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pc_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
