# Generated by Django 4.2.11 on 2025-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing_system', '0015_alter_customuser_pc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvaslayout',
            name='name',
            field=models.CharField(default='Unnamed Lab', max_length=10, unique=True),
        ),
    ]
